INSERT INTO WEBSITE (name, url, created_at) VALUES ('YouTube', 'https://www.youtube.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Google Maps', 'https://www.google.com/maps/', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Google', 'https://www.google.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Gmail', 'https://www.gmail.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Google Meet', 'https://workspace.google.com/products/meet/', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Google Photos', 'https://www.google.com/photos/', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Twitter', 'https://twitter.com/', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Facebook', 'https://www.facebook.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Instagram', 'https://www.instagram.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Threads', 'https://www.threads.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Snapchat', 'https://www.snapchat.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Messenger', 'https://www.Messenger.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('WhatsApp', 'https://www.whatsapp.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Telegram', 'https://web.telegram.com', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_at) VALUES ('Ymail', 'https://mail.yahoo.com', CURRENT_TIMESTAMP());
