INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('YouTube', 'https://www.youtube.com', 'Randy', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Google Maps', 'https://www.google.com/maps/', 'Luke', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Google', 'https://www.google.com', 'Lucas', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Gmail', 'https://www.gmail.com', 'Hannah', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Google Meet', 'https://workspace.google.com/products/meet/', 'Heidi', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Google Photos', 'https://www.google.com/photos/', 'Heike', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Twitter', 'https://twitter.com/', 'Ella', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Facebook', 'https://www.facebook.com', 'Süleyman', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Instagram', 'https://www.instagram.com', 'Sonia', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Threads', 'https://www.threads.com', 'Muhamed', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Snapchat', 'https://www.snapchat.com', 'Mercedes', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Messenger', 'https://www.Messenger.com', 'Debbie', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('WhatsApp', 'https://www.whatsapp.com', 'Sinezora', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Telegram', 'https://web.telegram.com', 'Carter', CURRENT_TIMESTAMP());
INSERT INTO WEBSITE (name, url, created_by, created_at) VALUES ('Ymail', 'https://mail.yahoo.com', 'Coert', CURRENT_TIMESTAMP());
